### ISSUE TITLE
Visually indicate the "installed" and "currently running" status of versions in the remote version list

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#10]
It would be helpful if the version list displayed by the `lsr` command had some kind of visual cue to indicate if any versions are already installed or if a version represents the currently running version. This way, I could run `lsr` and see if there is a newer version that what I've already installed/running, without needing to remember exactly which versions I have. This would just provide a shortcut for running `ls` and comparing the lists, but I like how the `ls` command already provides indication of running and default versions, and it would be cool if the `lsr` command provided similar context to better help read the data.

**Comment by jasongin** [comment]
Yes, it should indicate added, default and current versions.

**Comment by jasongin** [comment]
Done in https://github.com/jasongin/nvs/commit/044a7cd2dc78e83610c07bc5d6dac18827deca00

In addition to the `>` and `#` marks indicating current and default versions, the `*` indicates versions that are already added. (Processor architecture is ignored for these marks.)

```
$ nvs lsr 6
 >node/6.9.1 (Boron)
 *node/6.9.0 (Boron)
 #node/6.8.1
  node/6.8.0
  ...
```
