### ISSUE TITLE
NVS can't find binary for s390x?

### ISSUE THREAD

**Issue by gdams** [jasongin/nvs#100]
When I try to use NVS on linux s390x I get the following error:

```bash
$ nvs add 8
Platform package not available for version: node/8.11.4/s390x
```

I can't work out why this happens as a communtity release exists for s390x.

Steps to reproduce:

```diff
diff --git a/test/modules/versionTests.js b/test/modules/versionTests.js
index 0fd13f8..93b9026 100644
--- a/test/modules/versionTests.js
+++ b/test/modules/versionTests.js
@@ -125,6 +125,8 @@ test('Parse other architectures', t => {
        t.is(v.arch, 'arm');
        v = NodeVersion.parse('test/latest/arm64');
        t.is(v.arch, 'arm64');
+       v = NodeVersion.parse('test/latest/s390x');
+       t.is(v.arch, 's390x');
        v = NodeVersion.parse('test/latest/ppc64');
        if (os.endianness() == 'LE') {
                t.is(v.arch, 'ppc64le');
```

**Comment by kfarnung** [comment]
I took a quick look this morning and I think you want to modify the regex that's here:

https://github.com/jasongin/nvs/blob/c00d4fefee0678a2827b83a09ad5ebc0aa0840ef/lib/version.js#L7-L8

You will also want to modify this switch as well:

https://github.com/jasongin/nvs/blob/c00d4fefee0678a2827b83a09ad5ebc0aa0840ef/lib/version.js#L108-L126

Your original change just modifies the test code, so that's why it wasn't helping.

**Comment by gdams** [comment]
@kfarnung I have now tried changing the regex to this but still no luck?
```js
const versionRegex =
	/^(([\w-]+)\/)?((v?(\d+(\.\d+(\.\d+)?)?(-[0-9A-Za-z.-]+)?))|([a-z][a-z_-][0-9a-z_-]*))(\/((x86)|(32)|((x)?64)|(arm\w*)|(ppc\w*)|(s390x)))?$/i;
```

As for the switch, I'm not sure that is neccessary as it seems to be used to overwrite dfeaults (in this case s390x is correct).

**Comment by ljharb** [comment]
The reason is because that file only includes official releases.

**Comment by gdams** [comment]
is s390x not condered an official release @ljharb ?

**Comment by ljharb** [comment]
You said in your OP that it's a community release, which by definition isn't an official one - specifically, the only things that are official releases are things in nodejs.org's json indexes.

**Comment by kfarnung** [comment]
The binary is listed on the official download page:  https://nodejs.org/en/download/current/

I'll open a PR against the [indexer tool](https://github.com/nodejs/nodejs-dist-indexer) and see what people say.

**Comment by ljharb** [comment]
Apologies for the misunderstanding - altho what's on the website isn't necessarily "official", s390x is indeed available from dist: https://nodejs.org/dist/v9.9.0/ so it's just a bug that it's not in the json/tab files.

This should be closed in favor of https://github.com/nodejs/build/issues/1474

**Comment by kfarnung** [comment]
Thanks @ljharb!  I've opened a PR to fix the tool:  https://github.com/nodejs/nodejs-dist-indexer/pull/7

I think it's ok to leave this issue open for now to make sure NVS works once the index is updated.

**Comment by kfarnung** [comment]
@gdams I'm working on a PR that should enable s390x support once the index.json is updated.

**Comment by kfarnung** [comment]
@gdams I believe the changes will resolve the s390x issue once the index.json generator change is landed and the file is updated on the server.  If it still doesn't work feel free to reactivate this issue and I'll look into it further.

**Comment by kfarnung** [comment]
@gdams I tried out the master version of nvs and it looks like the s390x binaries are downloaded successfully.  I don't have a machine so I can only confirm that they don't run on my x64 machine. 👍
