### ISSUE TITLE
[Feature Request] Populate default aliases

### ISSUE THREAD

**Issue by digitalinfinity** [jasongin/nvs#11]
This is based on the observation that nvs add lts works but nvs use lts doesn't. It would be nice if nvs add <version label> would automagically create an alias of that label.

**Comment by jasongin** [comment]
I'm not sure about that. When you `nvs add lts` that looks for the *latest* LTS-tagged version available. But after you've added it, when you `nvs use lts` later does that need to check again what is the latest LTS-tagged version available? If so, that's different from a fixed alias. If not, then the meaning of `lts` isn't consistent between adding and using.

**Comment by jasongin** [comment]
Probably the way this should work is that you should be able to use `lts` and LTS-prefixed names like `lts-Boron` anwhere aliases work now. Those names require special handling different from aliass: index.json is needs to be fetched whenever they're used, or perhaps cached so it doesn't have to be fetched every time. And those LTS names wouldn't show up in the aliases list.

**Comment by digitalinfinity** [comment]
Actually I was thinking of something simpler. Maybe this could get confusing but the model I imagined was, nvs add would set the aliases at the point of add if you used a friendly name. So you do nvs add lts, then lts would continue to refer to that version until you did another add.
Too confusing?

_____________________________

**Comment by jasongin** [comment]
Done in https://github.com/jasongin/nvs/commit/044a7cd2dc78e83610c07bc5d6dac18827deca00

After you add an LTS-tagged release, the names  show up in your `nvs ls` output:
```
  node/7.1.0/x64
 #node/6.9.1/x64 (Boron)
  node/6.9.0/x64 (Boron)
 >node/6.8.1.x64
  node/4.6.2/x64 (Argon)
```

And you can refer to them by name when switching as `nvs use Boron` or `nvs use lts`. (With the exception of the `nvs add` command, these names always refer to the latest *locally* available version with that name.)

**Comment by digitalinfinity** [comment]
Sweet! Look forward to trying it out! Thanks @jasongin!

**Comment by jasongin** [comment]
Oh, after updating NVS, you will need to remove and re-add any LTS-tagged versions you had before in order for the added versions to include that metadata.
