### ISSUE TITLE
TravisCI: Node.js 10.12.0 downloaded for Node 6 env?

### ISSUE THREAD

**Issue by DanielRuf** [jasongin/nvs#110]
This seems a bit weird:

![bildschirmfoto 2018-10-19 um 13 28 29](https://user-images.githubusercontent.com/827205/47215794-fb5ae180-d3a2-11e8-9823-b99f60d4afc8.png)

**Comment by jasongin** [comment]
That is expected. The nvs tool is itself written in Node.js, so the first time you run it needs to download the node runtime. A small shell script takes care of that bootstrapping. For consistency it downloads a fixed version... I recently moved that version from node 6 to 10.
