### ISSUE TITLE
Read version from .nvmrc

### ISSUE THREAD

**Issue by dsbert** [jasongin/nvs#113]
I often switch between bash and powershell within the same project. It would be nice if `nvs` would also look for the current version in `.nvmrc` so the same version file can be used for this and https://github.com/creationix/nvm

**Comment by bnb** [comment]
+1 to this. I was literally just looking at `.node-version` documentation as I'm working on some tooling around it. Using `.nvmrc` would make my use case dramatically easier, since I'm already solving for it.

**Comment by RReverser** [comment]
One related issue that makes this particularly painful is that, if you rely on `.nvmrc` to provide a version number for Travis and don't want to duplicate a version in the `.travis.yml` too, then on Linux / OS X Travis will just read that file

https://github.com/travis-ci/travis-build/blob/47a407f9994b7c2f3907f7b4204acf44c57c3c83/lib/travis/build/script/node_js/manager/nvm.rb#L39-L42

invoke `nvm` and install correct version automatically.

However, on Windows, Travis uses `nvs add #{version}`

https://github.com/travis-ci/travis-build/blob/47a407f9994b7c2f3907f7b4204acf44c57c3c83/lib/travis/build/script/node_js/manager/nvs.rb#L30

which, in the absence of version in YAML, evaluates to just `nvs add`, and that fails any builds: https://travis-ci.com/v8/v8.dev/jobs/224821530

Given the specific name of `.nvmrc` and custom handling of it in Travis, I'm still not sure where is the best way to address this - in Travis itself or `nvs` - but right now there is no easy way to make the same build with `.nvmrc` work on all platforms.

**Comment by RichiCoder1** [comment]
I'd be game to either create or help with a PR that adds this capability until something more formal comes along.

**Comment by jasongin** [comment]
I'd be open to a PR that adds support for `.nvmrc` in addition to `.node-version`.

It could also make sense for `nvs add` with unspecified version to look for `.nvmrc` / `.node-version`. (Currently it requires a version on the command-line.) That would align with `nvs use` (with unspecified version) which does look for those files, and `nvs auto` (with no parameters) which is like a combination of both of those.

**Comment by RichiCoder1** [comment]
@jasongin Cool beans! I'll do some exploration this weekend, and if it looks easy to map at least 95% I'll submit a PR.

I'll look into nvs add too, that seems like a cool & reasonable ask especially in CI scenarios.

**Comment by RReverser** [comment]
Woohoo, thanks @jasongin and @RichiCoder1! I was pretty sure it would take more time and effort to convince interested parties, glad to be proven wrong! :)

Now I wonder what is Travis CI's release cycle / when they will pick up the changes.

**Comment by RReverser** [comment]
Looks like Travis has already upgraded to latest `nvs` and it works as expected. Thanks again! https://travis-ci.com/v8/v8.dev/jobs/226639190
