### ISSUE TITLE
NVS add error: Fail to download

### ISSUE THREAD

**Issue by Johant123456** [jasongin/nvs#124]
I have downloaded nvs 1.4.2 and installed it on Windows 10.
When I use the command nvs add latest I get this error messag: 
**Failed to download index: https://nodejs.org/dist/index.json
getaddrinfo ENOTFOUND nodejs.org nodejs.org:443**
Any Idea on how to debug this error?

**Comment by Johant123456** [comment]
I added proxysettings and it works.

**Comment by baileymatthewr** [comment]
What do you mean by "add[ing] proxysettings"? I'm also running into this error and would love to fix it.
