### ISSUE TITLE
What if I remove the current node version?

### ISSUE THREAD

**Issue by brodybits** [jasongin/nvs#13]
Actual (current): invalidates the `node` & `npm` commands in my current shell.

Is this desired? Should nvs select the default node version if it exists?

Also what if the user removes the default node version?

**Comment by jasongin** [comment]
What version of nvs are you using? In the latest version, removing the current version restores the default version, if there is one.

If you `nvs rm` the default version, then you won't have any `node` & `npm` commands in your shell unless/until you `nvs use` another version.

**Comment by brodybits** [comment]
Thanks!
