### ISSUE TITLE
Broken compatibility with Git Bash on Windows

### ISSUE THREAD

**Issue by KuttKatrea** [jasongin/nvs#133]
On Git Bash on Windows this line:

https://github.com/jasongin/nvs/blob/d28f6b16f3b78ad59bd686b5bc7f39232e2a787a/nvs.sh#L155

Produces the next error:

~~~
ps: unknown option -- o
Try `ps --help' for more information.
~~~

breaking compatibility.
Using the nvs.sh file from the inmediately previous commit (18fb267dbbff5189634cfd76c7157f936fc00615) works just fine.

NVS Version: 1.5.2 (with nvs.sh copied from the master branch on Github)
Git Version: git version 2.21.0.windows.1

**Comment by jasongin** [comment]
Thanks for pointing this out. The CI includes git bash tests, which passed, so I assumed the change was fine. But testing manually now I do see that error message. It doesn't prevent the rest of `nvs` functionality from working though.

@JimPatterson It looks like it should be fine to omit the `-ocomm=` part, do you agree? It seems to work in my testing.

**Comment by JimPatterson** [comment]
Yes, leaving the `-ocomm=` off should be just fine for most cases.  If a user had a username with bash in it, but was running ksh, it would see the bash in the username and think it was bash for the command.

I'll dig around to see if I can find another way to make it work that is git bash compatible...

**Comment by JimPatterson** [comment]
The username does not show by default in either linux or git-for-window `ps` output, so dropping the `-ocomm=` is safe.

**Comment by JimPatterson** [comment]
I created a pull request that fixes this problem.  I tested it on linux under bash and git for windows under bash.
