### ISSUE TITLE
Windows: when use npm prefix share global modules fails

### ISSUE THREAD

**Issue by betgar** [jasongin/nvs#137]
Steps to Reproduce:
1. use git bash (for window)
 ```bash
mkdir -p ~/.npm-global

# not ~/.npm-global/bin , i checked the files, there is no bin folder , weird
echo 'export PATH=~/.npm-global/:$PATH' >> ~/.bashrc

npm config set prefix ~/.npm-global
```
2. install global modules
```bash
npm i -g nrm

```

3. use global modules

```
# use cmd.exe
nrm ls
# can't find the command

```
** but use the git-bash everything is right **
```
# my .bashrc 
export NVS_HOME=$ProgramData/nvs
. $NVS_HOME/nvs.sh

#npm-global  $NPM_GLOBAL
export PATH=~/.npm-global/:$PATH
```
Expected result:
I hope i can share the npm global modules in this way .
Anyting wrong with my steps ? 

windows 10 1809
nvs 1.5.2
npm 6.9.0
node 10.16.0

**Comment by jasongin** [comment]
In `.bashrc`,  you explicitly added `~/.npm-global` to `PATH`. But the same was not done for `cmd.exe`? 

To manually add it to the user profile inherited by `cmd.exe`, you could use this `setx` command:
```
setx PATH "%PATH%;%USERPROFILE%\.npm-global"
```

Are you expecting `nvs` to do that automatically based on the custom npm prefix?

**Comment by ljharb** [comment]
fwiw, it’s not a good idea to share global modules across node versions. They’ll often be incompatible anyways.

**Comment by betgar** [comment]
I tried to add `%USERPROFILE%/.npm-globle` to the windows global system environments, but using the global module command under cmd.exe still doesn't work.
 Is there any way to automate execute `setx PATH "%PATH%;%USERPROFILE%\.npm-global" `
 every time when I start a new cmd.exe window?

**Comment by betgar** [comment]
Wow, thank you, you solved the problem that bothered me, because I use `cmder` and `cygwin` on both windows, after setting `setx PATH "%PATH%;%USERPROFILE%\.npm-global" ` , I need to log in again. All the terminals are in effect, great. Thx again.
