### ISSUE TITLE
Woes using nvs with sudo

### ISSUE THREAD

**Issue by codefoster** [jasongin/nvs#139]
I'm struggling to use nvs in Windows Subsystem for Linux (Ubuntu). Some `npm` commands like `install` or `up` will through EACCESS errors unless I use `sudo`. I solved that by turning off the `secure_path` in my `visudo`, but now I can't migrate my global packages from an old version of node installed via nvs. If I try to do the `nvs migrate` without `sudo` I get permission errors, but if I use `sudo` nvs says it can't find the installed version of node. I just want to be able to do everything without `sudo` ideally, or at least if I do have to use `sudo` to do things like install or upgrade global packages or migrate packages as I change node versions, I'd like for that to take effect for both `sudo` and non-`sudo`. Thanks.

**Comment by jasongin** [comment]
What is the path where is `nvs` installed? To avoid requiring `sudo`, I [recommend](https://github.com/jasongin/nvs/blob/master/doc/SETUP.md#mac-linux) installing it to a user location like `$HOME/.nvs`.

**Comment by codefoster** [comment]
That's where I have it. `which node` begets `/home/codefoster/.nvs/node/12.9.1/x64/bin/node`

**Comment by jasongin** [comment]
Hmm, I haven't had problems using `nvs` without `sudo` on WSL Ubuntu when installed under the user home.

Any of the `nvs` commands are only modifying files under `~/.nvs`, so if they require `sudo` it must mean some file ownership or permissions are wrong. Try fixing them like this:
```
sudo chown --recursive codefoster ~/.nvs
chmod --recursive a+w ~/.nvs
```

> if I use sudo nvs says it can't find the installed version of node

`nvs` includes an (undocumented) [`nvsudo` command](https://github.com/jasongin/nvs/blob/63c14aac2881bc129cad5ab1771c752d6d30edf4/nvs.sh#L145) that solves that problem. But you shouldn't need it after the above fix.

**Comment by codefoster** [comment]
I ran the permissions commands and it didn't seem to help. I think I installed nvs via scoop. Could that be a reason? I think my next step is to rip it out and try again.

**Comment by codefoster** [comment]
This is what I get if I run `npm install` without `sudo`...
```
Error: EACCES: permission denied, mkdir '/home/codefoster/.npm/_cacache/index-v5/74/08'
```

**Comment by jasongin** [comment]
I'm not familiar with scoop. But from reading about it now it looks like it's a Windows installer. I'd expect that would install nvs to somewhere that is not in your PATH in bash.

That last error seems to indicate the permissions problem is with the `.npm` cache directory. You could try the same commands to fix the permissions on that directory. You might have gotten into that state by initially running some `npm` command under sudo, which then created that directory with root ownership.

**Comment by codefoster** [comment]
Thanks for the help. I'll see what i can do.

**Comment by codefoster** [comment]
@jasongin, I did a `sudo rm -rf ~/.npm/_cacache` and it worked a treat. I'm now getting no errors on `npm install` or `nvs migrate`. Thanks for the help!
