### ISSUE TITLE
Linux on DeX support

### ISSUE THREAD

**Issue by wilmarques** [jasongin/nvs#141]
I'm trying to setup a development environment using [Linux on Dex](https://www.linuxondex.com/) but I can't install NVS on it. 

This is the error I'm facing:

![SmartSelect_20191003-162910_Linux on DeX Beta](https://user-images.githubusercontent.com/1015148/66157880-16961f80-e5fb-11e9-97ee-20b485b2e1bc.jpg)

In text mode:

```bash
Downloading bootstrap node from https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-aarch64.tar.xz                                 
###################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################### 100.0%                                                     
Failed to setup node binary.
```
The first two steps works correctly, as expected.

**Comment by jasongin** [comment]
Based on the output, I think the `tar` command failed to extract the downloaded archive. Try running this command manually, and you'll probably see a more specific error message:
```
tar -Jxvf "$NVS_HOME/cache/node-v10.12.0-linux-aarch64.tar.xz" -C "$NVS_HOME/cache" "node-v10.12.0-linux-aarch64/bin/node"
```

**Comment by wileymarques** [comment]
Just tried and this is the output:

```bash
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by wileymarques** [comment]
This is the url nvs ks trying to download node:

> https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-aarch64.tar.xz

It seems the system arch wasn't corectly recognized:

`linux-aarch64`

**Comment by wileymarques** [comment]
Well, itsn't incorrect, but aarch64 should be treated as arm64.

I'll try to place a PR.

**Comment by wilmarques** [comment]
Closing, as PR is merged
