### ISSUE TITLE
problem installing nvs

### ISSUE THREAD

**Issue by osso23** [jasongin/nvs#162]
HI,

           After setting the Path and cloning the repo, I get this error after I start installing in VS:
 "$env:NVS_HOME\nvs.ps1" install"

PS C:\Users\hp\Desktop\react-redux-firebase-authentication-master>  $env:NVS_HOME="$env:C:\Users\hp\Downloads\nvs"
PS C:\Users\hp\Desktop\react-redux-firebase-authentication-master> git clone https://github.com/jasongin/nvs "$env:NVS_HOME"
Cloning into '\Users\hp\Downloads\nvs'...
remote: Enumerating objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1543 (delta 2), reused 0 (delta 0), pack-reused 1537
Receiving objects: 100% (1543/1543), 909.64 KiB | 363.00 KiB/s, done.
Resolving deltas: 100% (1102/1102), done.
PS C:\Users\hp\Desktop\react-redux-firebase-authentication-master>  "$env:NVS_HOME\nvs.ps1" install
Au caractère Ligne:1 : 26
+  "$env:NVS_HOME\nvs.ps1" install
+                          ~~~~~~~
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

I am on Windows 10 and my Node version 14.0.0

**Comment by jasongin** [comment]
I'm guessing since you closed the issue you found the problem: to call a script in powershell, prefix it with a period and space:
```
. "$env:NVS_HOME\nvs.ps1" install
```
