### ISSUE TITLE
cant switch node version 

### ISSUE THREAD

**Issue by yuu2lee4** [jasongin/nvs#174]
i have two version installed of node,1412.0 and 14.13.1.The 14.13.1 ver is default,the 14.12.0 is current,when i use `nvs use 14.13.1`,the result of  command `node -v` is 14.13.1,but when i reopen the terminal,the curren version change to 14.12.0,the result of command `node -v` is 14.12.0.

os: macos 10.15.7
nvs: 1.6.0

**Comment by yuu2lee4** [comment]
After i rm the 14.12.0,i must use command `nvs use 14.13.1` every time when i open the terminal.

**Comment by jasongin** [comment]
The `nvs install` command ([doc](https://github.com/jasongin/nvs/blob/master/doc/SETUP.md#mac-linux)) should add a line to your `.bashrc`/`.zshrc` that will set up the node environment whenever a new shell is opened. Can you try running that (again)? Or does it not work?

**Comment by yuu2lee4** [comment]
I notice there is  aline `export PATH=~/.npm-global/bin:/Users/yuli/.nvs/node/14.12.0/x64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` in my `~/.zshrc`,but it not work after i delete `/Users/yuli/.nvs/node/14.12.0/x64/bin:/usr/local/bin` .

**Comment by yuu2lee4** [comment]
It worked after I deleted `export NVS_HOME="$HOME/.nvs"` and  ` [ -s "$NVS_HOME/nvs.sh" ] && . "$NVS_HOME/nvs.sh"` and excuted `. "$NVS_HOME/nvs.sh" install`
