### ISSUE TITLE
Migrate command seems to require architecture of source version

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#18]
I upgraded to NVS `v0.8.0`, added the latest Node version (`7.2.0`), and when I tried to migrate my current global NPM packages to it via `nvs migrate 7.1.0`, I got the following error: 

<img width="283" alt="screen shot 2016-11-26 at 2 01 43 pm" src="https://cloud.githubusercontent.com/assets/116461/20644176/20d727fe-b3e1-11e6-82d6-807e79afc25e.png">

Am I doing anything wrong? The `migrate` command has worked great up to this point, so maybe something regressed in the latest version? I'm running macOS Sierra, in case the issue is OS-specific. Thanks!

**Comment by lostintangent** [comment]
**Update:** I just tried running `nvs migrate node/7.1.0/x64` and it worked as expected. In the past, I didn't recall needing to specify the remote and/or architecture, but now it seems necessary. I only had one `v7.1.0` instead, across all remotes, so it would be ideal if it would allow specifying the "short name".

I can confirm that `nvs migrate 7.1.0/x64` or `nvs migrate default/7.1.0/x64` also work, however, if I didn't specify the `x64`, then I get the above error.

**Comment by jasongin** [comment]
Thanks for reporting! This was indeed a regression from the recent changes to how partial version strings are interpreted.

Fixed with https://github.com/jasongin/nvs/commit/771f4004b8568bc31cc90d2006e3c691893f9d79

**Comment by lostintangent** [comment]
@jasongin Just tested it and it works great!
