### ISSUE TITLE
Macbook Pro M1 Error: "Failed to setup node binary."

### ISSUE THREAD

**Issue by lidefang0918** [jasongin/nvs#182]
Install nvs in M1 success, but it dosn't work.
run any nvs command, throw the errorMessage  as below: 

MacBook-Pro ~ % nvs -v
Downloading bootstrap node from https://nodejs.org/dist/v12.18.4/node-v12.18.4-darwin-arm64.tar.xz
-#O#- #   #                                                                    
Failed to setup node binary.
MacBook-Pro ~ %

**Comment by jasongin** [comment]
Node.js does not yet publish builds for the Apple M1 (arm64), and when they do it will be for node v15 or later. It's possible to build binaries from source, but `nvs` does not support that.

For now, the x64 binaries should work fine via Rosetta 2, though with non-optimal performance. Try this:
```
arch -x86_64 zsh
nvs
```

Once you use `nvs` to download node x64 builds from within that x64 shell, you should then be able to run `node` and use `nvs`  to switch between versions from within a normal shell.

It could be possible to update `nvs` to handle this more automatically, by downloading and using x64 builds whenever an `arm64` build is not available for the requested version. Unfortunately I don't have an M1 system available to develop and test on. So, PRs are welcome!

**Comment by jasongin** [comment]
See also https://github.com/nodejs/build/issues/2474

**Comment by brodybits** [comment]
> See also [nodejs/build#2474](https://github.com/nodejs/build/issues/2474)

Do you think this will lead to worse download sizes?

**Comment by jasongin** [comment]
> Do you think this will lead to worse download sizes?

Based on the discussion in that issue about using fat binaries for the Mac OS builds starting in v16, yes I would expect the download on Mac OS to be larger then.

But meanwhile, `nvs` needs to be updated to automatically select `x64` instead of `arm64` when on Mac OS. That will work now (with the node v12 bootstrap download) and should continue to be correct even with node v16+, presuming the "fat binaries" are published as `x64`.

If anyone has an M1 Mac available to develop and test that fix on, a PR would be welcome!

**Comment by jasongin** [comment]
Fixed by 22fe78a

**Comment by shadowspawn** [comment]
From Node.js v16 there are separate downloads available for x64 and arm64 on Darwin. Inspecting the node binary with `lipo -archs` confirms they contain a single architecture.

https://nodejs.org/dist/latest-v16.x/

By contrast, based on the file size and online comments during the development of the Apple silicon native support, I think the `.pkg` contains a fat binary. (I have not inspected it to actually confirm.)

**Comment by jasongin** [comment]
The change above was to fix the boostrap node binary download, which is not on v16 yet (and will not be for a while).

Separately from that, using `nvs` to install Node v16 should correctly select `arm64` platform on Mac M1. I think that will require a small change [in `version.js` here](https://github.com/jasongin/nvs/blob/9f7d7b7f3e9b78e9ac4228b97dc04878f9f831a2/lib/version.js#L136). I don't have an M1 Mac to test on - can someone else test and submit a PR?
