### ISSUE TITLE
[Feature] Can NVS detect package.json's engines.node property ?

### ISSUE THREAD

**Issue by Sharlaan** [jasongin/nvs#184]
Along its current behavior detecting `.nvmrc` or `.node-version`, it would be nice if nvs could detect as well the **engines.node** property found in package.json

I met this usecase quite often among my clients whree they don't use nvmrc or node-version and don't allow me to add these files, but define an explicit engines.node version.
As a result i can't use nvs on a regular basis since i have to type systematically `nvs use <node version required by the project>` each time i use a new shell .... every day.
And yes i have tried nvs alias and link, but they don't persist per directory, and i feel a detection mode (like for nvmrc node-version files) sound more appropriate (and direct)

**Comment by ljharb** [comment]
`engines.node` is a version range, and thus is categorically not a good fit for selecting a single version of node (altho it's great for validating one) - for this reason, I think every node version manager has thus far chosen not to pay attention to that field.

**Comment by jasongin** [comment]
Yes, as @ljharb pointed out, `engines.node` declares the range of node versions that the package is known to be compatible with _at runtime_. Typically it is a wide range of versions, often encompassing EOL'd / insecure versions, and often unrestricted at the high end, e.g. `"node": ">=8.0.0"`. It's generally not a good source of guidance for auto-selecting a specific version to use. Another consideration is the dev dependencies may have more specific runtime node version requirements. For these reasons, a `.node-version` or similar file is more appropriate for this purpose.

**Comment by OJFord** [comment]
Ours is locked to major version, which makes sense to me for a closed-source binary/frontend where the only node users are also in control of the package.json.

I realise it's not really the purpose of `nvs`, but it'd be convenient to be able to use it as a shortcut to install the right version, the latest available that satisfies `engines.node`. (Plus for those that are using it anyway, needing another node version for some other reason.)
