### ISSUE TITLE
NVS_HOME is not under a well-known user or system directory

### ISSUE THREAD

**Issue by SturmB** [jasongin/nvs#185]
I'm attempting to run nvs on Ubuntu 20.04 in WSL2. I am getting this message **every time I run nvs**, including `nvs link lts` and even `nvs install`

```
NVS_HOME is not under a well-known user or system directory. Set the "linkToSystem" property in settings.json to true or false to specify whether NVS should link to into system directories.
```

It's been a long time since I installed nvs; did I do something wrong then? How do I fix this?

In addition, Attempting to run just `nvs` by itself yields:
```
The 'use' command is not available when invoking this script as an
executable. To enable PATH updates, source nvs.sh from your shell instead.
```

This is extraordinarily frustrating. I seem to remember using the `link` command before, but it's never persistent. Every time I started a new shell or rebooted, I'd have to run `nvs` again and pick the Node version installed. Now I cannot even do that!

**Comment by jasongin** [comment]
Sorry for the frustration. It sounds like you might have lost some configuration from the original install, probably your `.bashrc` was reset. You can re-run the installation with these commands:

```
export NVS_HOME="$HOME/.nvs"
. "$NVS_HOME/nvs.sh" install
```

After that, nvs will be configured for each new shell, including the linked default version.

**Comment by SturmB** [comment]
Thanks for the rapid reply, Jason!

You are correct, there was nothing in my `~/.zshrc` file. I wound up running almost the same thing that you suggested:
```sh
export NVS_HOME="$HOME/.nvs"
nvs install
```
And that seemed to alleviate everything after a shell restart. I didn't realize you could run the install command again after it had already been run once.

Sorry to have brought something so trivial here. Thank you again for your kind help, Jason, and take care!
