### ISSUE TITLE
Use in PowerShell for Linux?

### ISSUE THREAD

**Issue by rashil2000** [jasongin/nvs#190]
Hi! It's really nice to see a version manager that works consistently across OSes. However, the main reason I'm unable to use nvm.sh is because I use PowerShell everywhere. 

So I would like to know how I can source the nvs.sh so that I can use nvs in PowerShell on Linux.

**Comment by jasongin** [comment]
At the time I originally developed nvs, PowerShell was Windows-only. I haven't investigated what it would take to support PowerShell on Linux now, but I'm guessing sourcing `nvs.sh` is not going to work, at least not fully. Probably a better approach would be to update the `nvs.ps1` script to be cross-platform.

I probably won't have time to work on this anytime soon, but I'd be happy to review a PR if someone else wants to pick it up.

**Comment by rashil2000** [comment]
Is there a way for me to create a binary or a script for nvs (like nvs.exe for Windows) so that I can put it in `/usr/bin` and call it anywhere on Linux?

**Comment by rashil2000** [comment]
There are tools like [pkg](https://github.com/vercel/pkg) and [nexe](https://github.com/nexe/nexe) which can package Nodejs apps into standalone binaries, I wonder if it's possible to make use of those.

**Comment by jasongin** [comment]
Using a separate binary won’t work, for the same reason invoking `nvs.sh` from powershell doesn’t work: a separate process cannot modify the `PATH` environment variable in the _current_ shell. That is why nvs requires separate integration scripts for each kind of shell. The part of nvs that modifies the PATH works by sourcing a shell script in-proc from the calling shell.

**Comment by rashil2000** [comment]
Oh, I see. Thanks for the info!

**Comment by rashil2000** [comment]
I have beginner PowerShell knowledge, but looking at nvs.ps1 file, I think we only need to change the node binary's URL (for platforms other than Windows) and subsequent extraction command (7zr.exe). Is this correct?

**Comment by jasongin** [comment]
@rashil2000 That sounds right. And you might also need to change the detection of processor arch, as I don't know whether there is a `PROCESSOR_ARCHITECTURE` env variable on non-Windows platforms.

**Comment by rashil2000** [comment]
`[System.Environment]::Is64BitOperatingSystem` gives us the answer for that

**Comment by jasongin** [comment]
That's not enough if you're on an arm cpu.

**Comment by rashil2000** [comment]
ARM support in PowerShell was added fairly recently, I think - https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#support-for-arm-processors

For that reason, we can simply fallback to using `uname -m | sed -e 's/x86_64/x64/;s/i86pc/x64/;s/i686/x86/;s/aarch64/arm64/'`, as these commands will always be available on any *nix system

**Comment by rashil2000** [comment]
Hi, sorry for not getting back on this. 

I'm wondering if there's a much simpler way to achieve this: for Linux/macOS systems, the `nvs.ps1` script can call the script `nvs` (since it has a shebang it will work), simply as a one-time step to download the bootstrap binary and extract it. We would not need to rewrite all the tar extraction logic. Something like this:

```ps
if (-not (Test-Path $bootstrapNodePath)) {
  if (-not ($IsWindows -or $PSVersionTable.PSVersion.Major -eq 5)) {    
    & "$scriptDir/nvs" install
  } else {
  ...
}
```

Afterwards the `nvs.ps1` script can directly be used in Linux PowerShell sessions (some tiny path modifications might be needed in the script still).

If this is okay, I can try sending a PR for this.

**Comment by jasongin** [comment]
Yes, that's reasonable. As you said, there may still be some additional details to work out.

**Comment by rashil2000** [comment]
I have sent a PR, it's a very minimal change - #207 

Tested on Ubuntu 20.04.
