### ISSUE TITLE
[Feature Request] Allow omitting the minor and patch components when specifying a Node version

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#2]
It would be great if all commands which accepted a version flag allowed you to omit the minor and patch components, as long as NVS could resolve the correct version in an unambiguous way. For example, I'd love to be able to run `nvs use 6` and have it detect that I only have a single 6.* (e.g. `6.9.1`) version installed, and switch to it automatically. That way, I can have a 4.*, 6.* and 7.* release installed at the same time, and switch between them without needing to remember the exact version.

**Comment by jasongin** [comment]
Done in https://github.com/jasongin/nvs/commit/044a7cd2dc78e83610c07bc5d6dac18827deca00

Partial versions now work everywhere, including in .node-version files for auto-switching.

When a partial version matches multiple locally-available versions, the latest *local* version is chosen, except for an `nvs add` command where the latest *remote* version is chosen.

Let me know if you see any behavior that is unexpected.

**Comment by lostintangent** [comment]
@jasongin Works great! This definitely is a nice improvement to the UX :)
