### ISSUE TITLE
The ls and lsr commands don't support the "latest" version alias

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#20]
I really like how the `nvs add` and `nvs use` commands support the `latest` version alias in order to install and switch to the latest version that is available within a specific remote. However, I noticed that neither the `ls` nor `lsr` commands support the same capability. I would like to be able to quickly check what the latest available version is within a specific remote (e.g. `nvs lsr node/latest` or even `nvs lsr latest` to use my default remote), however, when I try that, the command simply outputs no value, but also, doesn't print an error.

Since the `nvs lsr` command supports the `lts` alias to find all `lts` versions, it seems reasonable for it to also support the same special `latest` value that other commands do, for the use case that I mentioned above. Since the `lsr` command will also indicate installed/current status of each version it lists, if you were to run `nvs lsr latest`, you could quickly see what the latest version is, as well as if you already have it and/or are already running it.

Supporting `nvs ls latest` is less valuable (at least to me now), but adding it would be ideal in order to be consistent across commands, which I think is important for the ergonomics/fluidity of the NVS CLI.

**Comment by jasongin** [comment]
I refactored and combined the version filtering and resolution logic used by the `ls`, `lsr`, and other commands, so they should be more consistent now. Fixed in https://github.com/jasongin/nvs/commit/085d6bdf31f91022686e2899eece1c7f9f5f6573
