### ISSUE TITLE
Alternatives for per-version global modules

### ISSUE THREAD

**Issue by marcelklehr** [jasongin/nvs#21]
Hey,
requiring to migrate (essentially copy?) global modules for every version seems like overkill to me.
I believe (correct me if this is not the case) that the node native API is compatible across all versions within a major version, so if that's the case would it make sense to have global modules per major version? I think this would be a big UX improvement.
But overall I really like your work so far. Great stuff!

**Comment by jasongin** [comment]
Good suggestion. However there are some potential complications:

* How would npm versions be handled? Currently the npm version used is the one that shipped with each node version. The npm minor version may differ between node minor versions, e.g. npm 3.10.8 with node 6.9.1 and npm 3.9.5 with node 6.2.2.
* Global modules would also need to be isolated per-processor-architecture and per-remote (fork). So then I'm concerned it could be confusing when global modules are shared between versions vs when they need to be migrated.

Still even given those issues it's definitely worth considering. Maybe as an option?

**Comment by marcelklehr** [comment]
I agree it's complicated. I have integrated npm version management in nodist and chose to have one global module folder only, I've been considering changing that for a while, though.

A completely different alley, would be to have all global modules always available but each using its own node version. This preserves the UX of 'install something once and it's always there', while keeping things working with changes to the global node version.

**Comment by ljharb** [comment]
Per my [comment](https://github.com/nodejs/version-management/issues/14#issuecomment-269030366), global modules must always be freshly installed on every version of node, in order to ensure everything works properly.

**Comment by jasongin** [comment]
Closing this based on @ljharb's [explanation](https://github.com/nodejs/version-management/issues/14#issuecomment-269030366) about why global modules need to be separated per-version, and @marcelklehr's [comment](https://github.com/nodejs/version-management/issues/14#issuecomment-269036780) that he is convinced.
