### ISSUE TITLE
nvsudo cannot use

### ISSUE THREAD

**Issue by Tim-Paik** [jasongin/nvs#214]
![image](https://user-images.githubusercontent.com/49786711/129329367-81429c71-831a-43de-a30c-c06e91355173.png)

How should I use the `nvs use` command when installing nvs globally?

**Comment by jasongin** [comment]
The instructions in [`SETUP.md`](https://github.com/jasongin/nvs/blob/master/doc/SETUP.md#mac-linux) for a system installation on Mac/Linux are wrong. I'll update those instructions, it should be something like this:
```
export NVS_HOME="$HOME/.nvs"
sudo git clone https://github.com/jasongin/nvs /opt/nvs
/opt/nvs/nvs install
```

With a system installation, `NVS_HOME` must still be set to a user-writable directory, e.g. `~/.nvs`, _not_ to the directory containing the `nvs` script files. `NVS_HOME` is where the user-specified node versions will be downloaded and cached, and also where that temporary `.sh` file can be written.
