### ISSUE TITLE
NVS cannot recognize node as LTS/Gallium version

### ISSUE THREAD

**Issue by qcyblm** [jasongin/nvs#218]
![image](https://user-images.githubusercontent.com/64412486/138997687-8762f926-dfbc-4637-8284-af9404f8b0fb.png)

**Comment by danstur** [comment]
I'm having the same problem - is there any workaround until this is fixed?

**Comment by Renari** [comment]
> I'm having the same problem - is there any workaround until this is fixed?

Seems to work if you use the full version number instead of the lts alias.

**Comment by segevfiner** [comment]
I believe I found the issue causing this: https://github.com/jasongin/nvs/pull/231

**Comment by jasongin** [comment]
Fixed by #231
