### ISSUE TITLE
Prefer arm64 binaries on Apple Silicon CPUs

### ISSUE THREAD

**Issue by ashsearle** [jasongin/nvs#219]
nvs currently defaults to downloading node binaries compiled for x64 on Apple Silicon.

This makes sense for node < 16, as there aren't any arm64 binaries available, but it would be nice if nvs defaulted to arm64 for Node 16+, to avoid the overhead of running node under Rosetta 2.

Note: arm64 binaries can already be installed and used with:
```bash
nvs add node/16/arm64
nvs use node/16/arm64
```

However: `nvs use 16` will fail, and stumbling across an `.nvmrc` containing `16` will trigger `nvs auto` to download/install/use the x64 version instead.

**Comment by jasongin** [comment]
See also #182 for some background.
