### ISSUE TITLE
[nvs link] Cannot read property 'split' of null

### ISSUE THREAD

**Issue by mrmlnc** [jasongin/nvs#24]
Hello, @jasongin, 

Firstly, thanks for **nvs**. This project looks a lot nicer than `nvm-windows`.

Unfortunately, I have a problem with the `nvs link` command. I'm use `cmd` from `ConEmu`.

```
$ ver & nvs -v & node -v & npm -v
Microsoft Windows [Version 10.0.14393]
0.8.3
v7.3.0
3.10.10

$ nvs ls
 >node/7.3.0/x64
  chakracore/7.0.0-pre10/x64

$ nvs link 7.3.0
Cannot read property 'split' of null
```

Data from my system and `console.log` 😄 in `link.js`:

```js
function linkToWindowsProfilePath(link, linkPath, isSystem) {
  link: true
  linkPath: C:\Users\Denis\AppData\Local\nvs\default
  isSystem: false

  profilePath: null
}

function getEnvironmentVariable(name, isSystem) {
  regKey: HKCU\Environment
  regLabel: user
  regValueType: REG_EXPAND_SZ

  child.stdout.toString(): ����� �����襭: ������� ᮢ�������: 0.
}
```

It seems to me that the problem is that I use Windows with Russian language Package.

If I run the command manually, I get:

```shell
$ reg.exe QUERY HKCU\Environment /V PATH /T REG_EXPAND_SZ
Поиск завершен: найдено совпадений: 0. // Translate: Search is finished: found matches: 0
```

If I run the command manually without `name`:

```shell
$ reg.exe QUERY HKCU\Environment /V PATH

HKEY_CURRENT_USER\Environment
    PATH    REG_SZ    C:\Users\Denis\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Denis\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs;C:\Users\Denis\AppData\Local\atom\bin;C:\Users\Denis\AppData\Local\nvs\
```

Works fine if I set:

```js
// ----------------\/ negative
let regValueType = (!/path/i.test(name) ? 'REG_EXPAND_SZ' : 'REG_SZ');
```

Let me know if I can help you 🌮

**Comment by jasongin** [comment]
Thanks for the bug report. It looks like the problem is an incorrect assumption that the `PATH` reg value is always type `REG_EXPAND_SZ` when apparently it can sometimes be type `REG_SZ`. I'll fix this soon.

**Comment by jasongin** [comment]
Fixed with https://github.com/jasongin/nvs/commit/00ab17f2504eb67cc86d11cd0621fe0025fc1ca9
