### ISSUE TITLE
Installation fails (macOS 10.12.2, zsh 5.2)

### ISSUE THREAD

**Issue by mologie** [jasongin/nvs#26]
Hello,

I've attempted to install nvs using the commands from README.md, but the installation fails with the following error.

Like mentioned in the title, my environment is macOS 10.12.2 with zsh 5.2 (shipped with the OS.)

```
$ export NVS_HOME="$HOME/.nvs"
git clone https://github.com/jasongin/nvs "$NVS_HOME"
. "$NVS_HOME/nvs.sh" install

Cloning into '/Users/oliver/.nvs'...
remote: Counting objects: 904, done.
remote: Total 904 (delta 0), reused 0 (delta 0), pack-reused 904
Receiving objects: 100% (904/904), 548.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (634/634), done.
nvs:29: = not found
```

**Comment by jasongin** [comment]
Hi, I was able to reproduce the problem, and I just pushed a fix. Please try again now:

```
cd $NVS_HOME
git pull
. "$NVS_HOME/nvs.sh" install
```

**Comment by mologie** [comment]
Thank you very much, I can confirm that the issue is resolved.

I hope that this project of your gains the popularity which nvm has, because its functionality and performance definitely trump that of nvm.
