### ISSUE TITLE
os.system("nvs use 14")   Failed to switch version

### ISSUE THREAD

**Issue by NoRainLand** [jasongin/nvs#280]
``` py
import os


def main():
    os.system("nvs -v")
    os.system("node -v") # now is 12.22.12
    os.system("nvs use 14") #PATH -= %LOCALAPPDATA%\nvs\default PATH += %LOCALAPPDATA%\nvs\node\14.21.3\x64
    os.system("node -v") # now is still 12.22.12


main()
```
 Failed to switch version

nvs -v  :1.7.0
python -v :3.8.5

**Comment by jasongin** [comment]
Sorry, this kind of out-of-proc use is not supported by `nvs`.

`nvs use` modifies PATH environment variable of the shell process that is executing the nvs script. But the python `os.system()` call _creates a new shell process_. So environment variable changes made by nvs do not affect the calling python process.

**Comment by NoRainLand** [comment]
:D
Thank you so much.
