### ISSUE TITLE
Automatically switch to default version after removing the currently running version

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#3]
If I'm running a version of Node, and I run `nvs rm` on it, my initial expectation was that NVS would actually switch me back to my default version (if one was set). That way if I'm experimenting with something in a nightly build (for example), and then I want to clean it off my system after I'm done, I don't need to run `nvs rm` and then `nvs use default` in order to get back to my default state. 

This is pretty low-priority behavior, and I suppose it's actually somewhat subjective whether it's the right thing to do, but I thought I'd log it as a conversation point :)

**Comment by jasongin** [comment]
Your expectation makes sense. I consider it a minor bug.

**Comment by jasongin** [comment]
This bug is fixed in the `auto` branch, as part of the work described at #4.

**Comment by lostintangent** [comment]
@jasongin Awesome! Both changes work beautifully.

**Comment by jasongin** [comment]
Fixed as part of https://github.com/jasongin/nvs/commit/93f3cde85623e44512cec1c51f54fa2d4b905c08
