### ISSUE TITLE
Chocolatey publication

### ISSUE THREAD

**Issue by mrmlnc** [jasongin/nvs#31]
I would be happy to see the NVS in Chocolatey for automatic installation on the new machine(s).

Documentation: https://chocolatey.org/docs/create-packages

**Comment by jasongin** [comment]
Yes. And probably also `brew` for Mac OS. I'm not very experienced with either, but I'll look into this when I have time, unless someone else wants to contribute.

**Comment by wadetb** [comment]
It would be nice to support [scoop.sh](https://github.com/lukesampson/scoop) as well. For comparison with Chocolatey, see https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison.

Documentation: https://github.com/lukesampson/scoop/wiki/Creating-an-app-manifest

**Comment by molant** [comment]
I'm looking into publishing NVS in chocolatey to improve as part of the improvements of [windows-dev-box-setup-scripts](https://github.com/Microsoft/windows-dev-box-setup-scripts/issues/46) I'm working on.

There are a few files that are needed to publish in chocolatey (a few `.ps1`, `.nuspec`, etc.). I was planning on creating a new repo on my account and maintain it myself until I saw this issue. How do you want to proceed? Are you ok with that? Want me to try to get everything integrated in this repo? I don't see any publishing script in here to connect everything together so I'll probably create a separate folder for this and set up an npm script to do the magic.

Thanks!

**Comment by jasongin** [comment]
If it's OK with you, I'd prefer to have it in this repo so it's easier for others to discover, and I can keep track of what's happening with it, and track issues in the same place. We can start with a PR, but if you're going to be maintaining it then I can give you push access so you don't have to be blocked on me.

Thank you!

**Comment by molant** [comment]
@jasongin sure, makes sense. I just did a PR and some comments around things I'm unsure of the metadata.
