### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by kfarnung** [jasongin/nvs#35]
I downloaded and installed nvs 1.0.1 on a Windows 10 1607 VM running in VirtualBox.  When I attempt to run `nvs` I get the following error:

```
C:\Users\kfarnung>nvs
Cannot read property 'startsWith' of undefined
```

I believe previously this would bring up the interactive menu.  I still seem to be able to use the command-line options to switch versions.

**Comment by ljharb** [comment]
I recommend using https://www.npmjs.com/package/airbnb-js-shims in nvs' copy of node to ensure that all the standard APIs you expect are both present and working properly.

**Comment by kyrylkov** [comment]
+1 

same problem after upgrading from nvs 0.8.x to 1.0.1

@ljharb what does invoking freshly installed nvs has to do with shims?

**Comment by jasongin** [comment]
Fixed by https://github.com/jasongin/nvs/commit/5408e788c1708b130643523474c9cea98753098a for version 1.0.2.

This bug slipped through because there is not currently any test coverage for the command-line parsing. I will add for that area to make sure something like this doesn't happen again.

**Comment by jasongin** [comment]
@ljharb nvs downloads a specific known-good version of node for private use. Running it with some arbitrary older version of node is currently unsupported. But if nvs ever *does* need to support that scenario then the library you mentioned looks like it could be useful.

**Comment by kyrylkov** [comment]
@jasongin 1.0.2 works fine again. Thanks!

**Comment by jasongin** [comment]
Thanks for the confirmation. I'm going to leave this issue open for a few days just in case anyone else comes looking for info.
