### ISSUE TITLE
option for non-interactive default mode

### ISSUE THREAD

**Issue by rmg** [jasongin/nvs#38]
I live in my shell and generally speaking the only interactive command I run is `vim` (either directly or via `git commit`/`git rebase -i`) and it is kind of annoying that running `nvs` without any arguments drops me in to an interactive session instead of just printing out a usage statement.

I realize it is probably my UNIX-beard screaming and that the majority of the target audience probably _like_ this interactive mode, it would make me so very happy if there was an env var something I could set to change the default mode to match `nvs help`.

**Comment by gibfahn** [comment]
I have the same issue, I'd rather have something else for interactive, but I agree it probably shouldn't be on by default.

Or maybe interactive mode could also print out the usage? Might get a bit long, idk.

**Comment by jasongin** [comment]
Good idea. I personally never use the interactive menu either, but I know some people use it exclusively. It would be easy to add a setting to disable the interactive menu, stored in settings.json.

**Comment by rmg** [comment]
I hadn't even gotten far enough in exploring `nvs` to notice there's a `settings.json`. I see the remotes and aliases get stored in there as well. Makes sense.

**Comment by rmg** [comment]
@jasongin is there anything special about how _you_ would do this, before I start poking around at it myself?

**Comment by jasongin** [comment]
The clear part to me is to define a setting name in settings.json that enables/disables the menu. I think you shouldn't need to change any code in settings.js; just add a check for the setting name in main.js before displaying the menu. Then at least one can manually edit settings.json to change it.

Beyond that, I'm unsure whether there should be a command to change the setting (or a general set of commands to edit preferences, in case there are more?) or maybe an option in the menu to disable itself. I'm open to feedback on that.
