### ISSUE TITLE
Automatically switch versions based on per-directory config

### ISSUE THREAD

**Issue by jasongin** [jasongin/nvs#4]
This feature is under development in the [auto](https://github.com/jasongin/nvs/tree/auto) branch. Currently it is working pretty well for PowerShell. If anyone would like to preview this feature and provide early feedback, checkout that branch and read details here: https://github.com/jasongin/nvs/blob/auto/doc/AUTO.md

I still need to do some more testing, and implement equivalent functionality for POSIX, probably using the same mechanism as [nodengine](https://github.com/Kikobeats/nodengine).

The best part of this feature won't be available to Windows Command Prompt users, since there is no way there (AFAIK) to hook into directory changes. However they can still manually run `nvs auto` at any time to trigger the same search for per-directory config.

**Comment by jasongin** [comment]
@marcelklehr tagging you since you were interested.

**Comment by jasongin** [comment]
I finished and merged this feature. It works in both PowerShell and Bash.
https://github.com/jasongin/nvs/commit/93f3cde85623e44512cec1c51f54fa2d4b905c08
https://github.com/jasongin/nvs/commit/b29febb4fde9d508994b05658f69a8fa4304f8c6

**Comment by marcelklehr** [comment]
Thanks for tagging me. It's an interesting route, different from the one I took. I'm looking forward to discussing this in the WG and to hear about your experiences with it :)
