### ISSUE TITLE
Support for git bash on Windows

### ISSUE THREAD

**Issue by jonaskello** [jasongin/nvs#41]
```
$ export NVS_HOME="$HOME/.nvs"

$ git clone https://github.com/jasongin/nvs "$NVS_HOME"
Cloning into 'U:/.nvs'...
remote: Counting objects: 965, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 965 (delta 3), reused 0 (delta 0), pack-reused 956
Receiving objects: 100% (965/965), 575.87 KiB | 409.00 KiB/s, done.
Resolving deltas: 100% (676/676), done.

$ . "$NVS_HOME/nvs.sh" install
Downloading bootstrap node from https://nodejs.org/dist/v6.10.0/node-v6.10.0-mingw64_nt-10.0-x64.tar.xz
######################################################################## 100,0%
mv: cannot stat '/u//.nvs/cache/node-v6.10.0-mingw64_nt-10.0-x64/bin/node': No such file or directory
rm: cannot remove '/u//.nvs/cache/node-v6.10.0-mingw64_nt-10.0-x64': No such file or directory
Failed to download boostrap node binary.

```

**Comment by jasongin** [comment]
Hi @jonaskello,

NVS does not currently support git bash on Windows. Please use Command Prompt, PowerShell, or [Bash on Ubuntu on Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/about) instead.

From the output above, I see two problems:

1. `$HOME` is empty. I don't know why that is, since when I run git bash `$HOME` is set to `/c/Users/<username>`.
2. The platform detection doesn't work properly, so it tries to download `node-v6.10.0-mingw64_nt-10.0-x64.tar.xz`, which doesn't exist. The `nvs.sh` script uses `uname` to detect the platform, which on Git Bash on Windows returns `MINGW64_NT-10.0`, when actually a node-supported platform name like `linux` or `darwin` is expected.

Even if those issues are resolved, I think there are likely to be further problems because Git bash on Windows doesn't provide a complete Linux environment. But it could probably be made to work if someone wants to spend some time on it.

**Comment by jonaskello** [comment]
@jasongin Thanks for the reply!

I mostly do JS/TS development and don't really use cmd as most scripts in package.json files assumes bash. I tried ubuntu on windows but it is too incomplete to use for any real development in JS (eg. file watching is missing). I know it has been updated and file watching added etc. but from what I gather the only way to get it to update is to run a development build of the whole Windows 10 OS?

The reason I wanted nvs was to try out (node-chakracore)[https://github.com/nodejs/node-chakracore]. I guess a lot of JS developers on windows still have gitbash as their shell because of the above reasons. Just to clarify, there is currently no workaround available to use nvs with gitbash?

**Comment by jonaskello** [comment]
Seems like ubuntu on windows will be updated in Windows Creators update next month. I guess I can wait until then to try node-chakracore :-).

**Comment by jasongin** [comment]
@jonaskello Note that the NVS-managed version of node in the Ubuntu on Windows environment will actually be the Linux version, that is not usable from other Windows apps outside of the Ubuntu environment, so for that reason it might not fit with your workflow.

I will investigate what it will take to make NVS compatible with git bash; maybe it won't be too hard. So I'm reopening this issue to track that effort.

Also, it is still possible to use node-chakracore without NVS. It just involves more manual steps:
 * Download the Windows .zip package from https://github.com/nodejs/node-chakracore/releases
 * Extract to a local directory
 * Add the directory to your PATH

**Comment by jonaskello** [comment]
Thanks for considering this! I'll try the manual install steps for now and see if it works in gitbash.

**Comment by jasongin** [comment]
I added git bash support in the NVS **develop** branch as https://github.com/jasongin/nvs/commit/d9f82ec0ae14d62952ca2d720300e4a763448c90

Can you clone the NVS develop branch and give it a try? I don't normally use Git bash, but in my limited testing it seems to work now. I'd like to get confirmation before I merge this change into the master branch. Thanks!

**Comment by jasongin** [comment]
Also I added [documentation](https://github.com/jasongin/nvs/blob/2fc18947962a61b551ab373681cb087b501a81c0/doc/SETUP.md#git-bash-on-windows) for setting up NVS to work in Git bash.

**Comment by jonaskello** [comment]
I got it working but there were some things to note:

First I followed the regular cmd instructions to set it up for all users. In doing so I think I found an error in the documentation. This [line](https://github.com/jasongin/nvs/blame/2fc18947962a61b551ab373681cb087b501a81c0/doc/SETUP.md#L23) says `git clone https://github.com/jasongin/nvs "%NVS_HOME"` but I had to change it to `git clone https://github.com/jasongin/nvs %NVS_HOME%`, otherwise it would create a dir named `%NVS_HOME`.

Then I noticed that my `$HOME` in gitbash was set to `/u`. This seems to be because in `cmd` I have these variables set:

```
C:\WINDOWS\system32>set
...
APPDATA=C:\Users\jonkel.DIVID\AppData\Roaming
ProgramData=C:\ProgramData
...
HOMEDRIVE=U:
HOMEPATH=\
```

So it seems gitbash sets `$HOME` based on `%HOMEDRIVE%` and `%HOMEPATH%` from `cmd`.

Because of this, when I follow the docs for gitbash installation and add this:

```
export NVS_HOME=$HOME/AppData/Local/nvs
. $NVS_HOME/nvs.sh
```

I get this error when a start a new gitbash shell:

```
bash: /u//AppData/Local/nvs/nvs.sh: No such file or directory
```

But it seems gitbash mirrors all the `%FOO%` variables from `cmd` so to get it to work I could instead add this:

```
export NVS_HOME=$ProgramData/nvs
. $NVS_HOME/nvs.sh
```

**Comment by jasongin** [comment]
> `git clone https://github.com/jasongin/nvs "%NVS_HOME"`

Yes that's a typo, thanks for pointing it out! I'll fix it.

> $HOME in gitbash was set to /u

Was it set to `/u` or `/u/`? I wonder where the double-slash came from in the bash error message. I wouldn't normally expect `$HOME` to have a trailing slash, so maybe it is a Git bash bug?

> export NVS_HOME=$HOME/AppData/Local/nvs

As you figured out, the intention here is that you need to point it to wherever you have installed NVS. That is the most common installation location but it could be under ProgramData or any custom location. I'll try to clarify the documentation.

Anyway thank you for confirming that this works for you.

**Comment by jonaskello** [comment]
It had a trailing slash:
```
$ echo $HOME
/u/
```
My guess it that is converts HOMEDRIVE=U: into `/u`and `HOMEPATH=\` into `/` and then concats them into `/u/`. There's some info [here](https://groups.google.com/forum/#!topic/msysgit/5RiG2D96iHo) but it might be old.

**Comment by jasongin** [comment]
I merged this into master. Since this is a new capability I bumped the semantic version to 1.1.0.
