### ISSUE TITLE
Broken on non-Windows

### ISSUE THREAD

**Issue by rmg** [jasongin/nvs#43]
It appears that the changes in d9f82ec0ae14d62952ca2d720300e4a763448c90 to add support for git bash on Windows inadvertantly broke bash support on macOS (and I suspect Linux).

It appears to turn all POSIX paths to Windows paths, which results in a new directory in `$NVM_HOME` that is the fully expanded version of itself with the slashes reversed.

**Comment by jasongin** [comment]
Oh no! Thanks for reporting this. I just fixed it as https://github.com/jasongin/nvs/commit/16a7544812181dd04b80ec079099a89ec7777780

I'm usually more careful about cross-platform testing.

**Comment by rmg** [comment]
Thanks. Just verified 👍
