### ISSUE TITLE
Use numeric instead of lexicographic sort order (or sort by date published)

### ISSUE THREAD

**Issue by dilijev** [jasongin/nvs#48]
```
.-----------------------------.
| Select a chakracore version |
+-----------------------------+
|  a) chakracore/7.0.0-pre9   |
|  b) chakracore/7.0.0-pre8   |
| [c] chakracore/7.0.0-pre10  |
|  d) chakracore/6.0.0-pre7   |
|  e) chakracore/6.0.0-pre6   |
|  f) chakracore/6.0.0-pre5   |
|  g) chakracore/6.0.0-pre4   |
|  h) chakracore/6.0.0-pre3   |
|  i) chakracore/6.0.0-pre2   |
|  j) chakracore/6.0.0-pre1   |
'-----------------------------'
```

In the above, 7.0.0-pre10 should be at the top of the list. It behaved the correct way in 0.9.1.

**Comment by jasongin** [comment]
Technically these are sorted correctly according to the [semver spec](http://semver.org/#spec-item-11):

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and **identifiers with letters or hyphens are compared lexically** in ASCII sort order.

So, I think this is a bug in node-chakracore's use of semver prerelease tags. I'm not sure whether there should be a special case for that in nvs.

**Comment by dilijev** [comment]
Good point. I guess the fix should happen on ChakraCore's side.
