### ISSUE TITLE
Why not change path permanently?

### ISSUE THREAD

**Issue by vickylance** [jasongin/nvs#53]
Hi,

I did not install node using the installer from nodejs website instead, I directly downloaded and installed nvs and using it, I installed nodejs and nodejs-chakra.
However, after setting a version to use it is not setting permanently updating the PATH. Meaning its using "set" instead of "setx". And sets the path only for that instance of the cmd.
So every time I open a cmd I have to select the version I want and then I have to start to work. So why not set it permanently and also permanently change everytime I nvs use a version?

**Comment by jasongin** [comment]
The `nvs use` effect is intentionally local to the current shell. That enables you to use different node versions in different shells.

If you want to set a version that is used by default in any new shell, use the [`nvs link`](https://github.com/jasongin/nvs/blob/master/doc/LINK.md) command. That also updates the system `PATH`.

**Comment by vickylance** [comment]
@jasongin Ah, ok my bad. Thank you. And thanks for the quick response 👍
