### ISSUE TITLE
Doesn't work with v8-canary repo

### ISSUE THREAD

**Issue by kyrylkov** [jasongin/nvs#57]
Doesn't work with `v8-canary` repo https://nodejs.org/download/v8-canary:

```
C:\Users\user\dev\bluebird>nvs
Downloading [########################################################################################################################################################################] 100%
Extracting  [########################################################################################################################################################################] 100%
Specified version not found.
To add this version now: nvs add v8-canary/9.0.0-v8-canary20170622fbb8f9c731/x64
```
![image](https://user-images.githubusercontent.com/6225870/27485624-21f80348-5836-11e7-82e5-98c47fff3778.png)

**Comment by jasongin** [comment]
This was fixed recently as https://github.com/jasongin/nvs/pull/56, so it should work with NVS v1.2.1.

Sorry I haven't published a NVS Windows release since then. I will do that, but meanwhile you can get it with a git clone.
