### ISSUE TITLE
Unable to install v1.4.2 on Windows 10

### ISSUE THREAD

**Issue by vickylance** [jasongin/nvs#65]
Hi I already have nvs installed on my machine. But when I try to update to the latest version I am geting an error. Also I have tried uninstalling existing nvs but still I am getting this error.
Here is a screenshot,
![capture1](https://user-images.githubusercontent.com/5861833/28476730-b63de8a8-6e6e-11e7-9040-25f345d41943.PNG)

I am getting the error as 2318. Please help me with this.

**Comment by vickylance** [comment]
I have also tried downloading the package multiple times. And it is downloading perfectly so nothing is wrong with the package.

**Comment by jasongin** [comment]
Known issue. See https://github.com/jasongin/nvs/issues/22 for workarounds.
