### ISSUE TITLE
Fails to download bootstrap node on 32-bit intel linux

### ISSUE THREAD

**Issue by creationix** [jasongin/nvs#67]
```sh
tim@eeepc:~/.nvs$ nvs install
Downloading bootstrap node from https://nodejs.org/dist/v6.10.1/node-v6.10.1-linux-i686.tar.xz
######################################################################## 100.0%
Failed to download boostrap node binary.
```

Looking on the node server, the url we want is <https://nodejs.org/dist/v6.10.1/node-v6.10.1-linux-x86.tar.xz>

My kernel reports `i686` as the architecture:

```sh
tim@eeepc:~/.nvs$ uname -a
Linux eeepc 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:09:08 UTC 2017 i686 i686 i686 GNU/Linux
```

**Comment by creationix** [comment]
Heh, I just noticed, what exactly is a "boostrap" node binary?  That sounds kinda scary. 🎃

**Comment by ljharb** [comment]
iirc, nvs downloads its own copy of node, so it can run the majority of its commands in JS instead of posix/windows (which the bootstrap script has to run in)

**Comment by ljharb** [comment]
lol nvm i get the joke now
