### ISSUE TITLE
Support ayojs fork?

### ISSUE THREAD

**Issue by brodybits** [jasongin/nvs#70]
<https://www.infoq.com/news/2017/09/Node-JS-Forks>

It looks like ayojs will support worker threads ref: https://github.com/ayojs/ayo/pull/40

**Comment by jasongin** [comment]
`nvs` already supports any forks that publish releases in the same format as node. Just use the `nvs remote` command to add the URI to the releases root folder.

Does ayojs publish releases? I can't find any.

**Comment by brodybits** [comment]
> `nvs` already supports any forks that publish releases in the same format as node.

This is not so clear from README.md. I would be happy to contribute a doc patch.

It would also be nice to support GitHub branch/commit. Not sure when I can work on this idea.

**Comment by jasongin** [comment]
> This is not so clear from README.md

Yes, while the readme mentions "support for different forks", it doesn't clarify the requirements for a supported fork, which is basically just to publish release binaries in the same format as https://nodejs.org/dist/

> It would also be nice to support GitHub branch/commit.

`nvs` doesn't currently support building node binaries from source. I have no plans to work on that, but if someone else is motivated then I'd be open to it.

**Comment by brodybits** [comment]
Thanks for the response, closing as ayojs *seems* to be dead now.
