### ISSUE TITLE
Is there a way to upgrade node without reinstalling all the globally installed modules?

### ISSUE THREAD

**Issue by vickylance** [jasongin/nvs#72]
So I want to upgrade the nodejs version that I installed via nvs. And now I want to upgrade my Nodejs version without going through the painful process of checking what are the npm modules that I have installed in my current version and then again installing them on the latest updated version of Nodejs.

Is there any command or a simpler way to do it?

**Comment by jasongin** [comment]
Sorry for the delayed response... Did you find the `nvs upgrade` command?

Let me know if that doesn't do what you wanted.
