### ISSUE TITLE
Missing bash support on Windows

### ISSUE THREAD

**Issue by oliversalzburg** [jasongin/nvs#74]
The POSIX shell scripts are missing when installing nvs on Windows. This complicates using it when using bash as a shell.

When I manually placed the shell scripts in the installation directory, I could see no issues. So I don't understand why they are not included.

As a side note: Putting the linking at the bottom of the README is not ideal IMHO. When I install the first version of Node, not having it persisted is counter-intuitive if you're coming from other Node version management tools.

**Comment by brodybits** [comment]
I would recommend the following kind of workaround solution, which works like a charm for me:

First do normal installation on Windows. (I did installed it from MSI almost 2 years ago.)

Then try installing and using recent Node.js versions from cmd or similar tools such as cmder. (I would **highly** recommend trying cmder out. I do not find installation 100% intuitive, would now highly recommend considering using scoop.sh to install cmder and similar tools on Windows.)

I generally use "MinGW64" bash from git bash, which seems to be installed by scoop.sh when installing git update. (I forget whether or not this was part of scoop install cmder.)

At this point, I am able to use the same Node.js installation from the same nvs installation on cmd, cmder, and MingW64 (git) bash.

**Comment by jasongin** [comment]
Fixed by #149
