### ISSUE TITLE
Differences with NVM

### ISSUE THREAD

**Issue by juancampa** [jasongin/nvs#75]
Hi, this project caught my attention while going through the readme of https://github.com/mrkmarron/RFSDemoJS but I was wondering. Are there any particular reasons for me to use `nvs` over `nvm`?

The readme mentions that it's inspired by nvm but that's it

Thanks

**Comment by jasongin** [comment]
* It's cross-platform. (While there is an `nvm-windows` project, it's completely different from `nvm`.)
 * It supports easy switching between different forks of node, like `node-chakracore`.
 * It's written in node JavaScript, so easy for node developers to contribute to.

**Comment by juancampa** [comment]
Thansk @jasongin. That's pretty compelling! You might want to put it in the readme.

**Comment by ljharb** [comment]
fwiw, `nvm` works fine on Windows on BashOnWindows/WSL :-p
