### ISSUE TITLE
Allow filtering the remote version list by LTS release name

### ISSUE THREAD

**Issue by lostintangent** [jasongin/nvs#9]
I really like how the `lsr` command allows filtering the results by version range (e.g. `4`, `6.9`). Since the results also display the LTS release name next to relevant versions (e.g. `Argon`, `Boron`), it would be cool if you could use that string as a filter in order to see just versions which are a part of a specific LTS release. For example, that would allow users to easily check if there are any new updates for the Node v6 LTS release, without needing to remember that it corresponds to `v6.9.*` (e.g. `nvs lsr node Boron`). This can be pretty easily achieved via `nvs lsr node | grep Boron`, so this is more of a "fit-n-finish" request, that I'm not sure whether other users would find that valuable.

**Comment by jasongin** [comment]
Yes, sounds like a good idea.

**Comment by jasongin** [comment]
Done in https://github.com/jasongin/nvs/commit/044a7cd2dc78e83610c07bc5d6dac18827deca00

Any of these commands work now:
```
nvs lsr lts
nvs lsr Boron
nvs lsr node/lts
nvs lsr node/Boron
```

And, you can see and refer to LTS-tagged versions by name after you add them locally. See https://github.com/jasongin/nvs/issues/11
